# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='passport',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Паспорт'),
        ),
    ]
